### ISSUE TITLE
Render on Drag or Resize

### ISSUE THREAD

**Issue by OAguinagalde** [dotnet/Silk.NET#241] opened 2020-07-15 09:26 UTC
Hello, this might not be the correct place to ask, but just in case. How would I go about rendering to the window even if I'm resizing/dragging the window around?

I've tried playing around with the Move event and the UseSingleThreadedWindow window option but can't manage.

Thanks!

**Comment by Perksey** [comment] 2020-07-15 14:12
Hi there, thanks for using Silk.NET!

Sadly this is caused by a fatal flaw baked into the message loop of the Desktop Window Manager that GLFW, our underlying window library, is subject to.

Basically Windows has a message loop that all events are put into, however when you drag or resize a window it actually halts that message loop until you've put it back down, so yeah this is a bug but it's a bug that's become part of the core design and isn't one we can't fix sadly, due to it beign an upstream issue.

If you'd like, you could have a play around with setting up a custom game loop (the source code for the one built in to the library is [here](https://github.com/Ultz/Silk.NET/blob/554af444457e52691cf87c479f9c9a5c77f1ff59/src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs/#L44)) and mess around with how/when you call the DoEvents function, as that's the call that blocks.

Other than that there's not really much that can be done to alleviate this. Sorry!

**Comment by OAguinagalde** [comment] 2020-07-20 01:15
I see, got it. Thanks for the reply, I'm not sure I'm up to the task but I might give it try. Thanks again!

**Comment by Arugin** [comment] 2024-02-17 08:42
About resizing: 
One way that works: add two calls to drawFrame() in the resize callback. Two calls because the first after each resize will only recreate the swap chain, need a second call to get the actual render.

**Comment by Perksey** [comment] 2024-04-15 03:52
Closed in #1979 as best we can at this time - you can now render while the message loop is blocked so long as things are actually happening. So if you drag, each pixel change gives you an opportunity to redraw. But if you hold the window still, no drawing will occur. This is a limitation we are unprepared to overcome at this time.

**Closed by Perksey** 2024-04-15 03:52 UTC
Labels: bug, wontfix, area-Windowing, upstream
