### ISSUE TITLE
IsVisible = Crash, Can't create window either way

### ISSUE THREAD

**Issue by B0M** [dotnet/Silk.NET#578] opened 2021-08-13 17:55 UTC
# Summary
Window instance cannot be created. In one setting, this will crash the entire OS into the login screen.

# Steps to reproduce
- Platform: MacOS High Sierra 10.13.6
- Framework Version: .NET Core 3.1
- API: OpenGL
- API Version: OpenGL 3.2 Core
Run Hello Window with IsVisible = true for window options.
Crash to login.

# Comments
I've tried with all other options including the necessary forward compatibility for MacOS. Window instance refuses to be created even when it doesn't crash.

**Comment by Perksey** [comment] 2021-08-13 18:15
Note: this is on an old version of macOS, Apple only tend to support 3 macOS versions at a time so if we can't fix this it's not really much of a concern. Need to try and reproduce this on Big Sur.

**Comment by Perksey** [comment] 2021-08-13 18:37
Can't reproduce.

<img width="1939" alt="Screenshot 2021-08-13 at 19 34 12" src="https://user-images.githubusercontent.com/11160611/129404152-bfec744d-f758-494e-93b7-a585cad2a443.png">

**Comment by Perksey** [comment] 2021-08-16 13:30
Closing due to being unable to reproduce.

**Closed by Perksey** 2021-08-16 13:30 UTC
Labels: bug, wontfix, area-Windowing
