### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by Khitiara** [dotnet/Silk.NET#1437] opened 2023-05-01 03:34 UTC
Currently the prerelease builds on the experimental feed are a lower version number than the last actual release; I propose that the patch number should be bumped on main as even if whatever release comes next warrants increasing the minor version number both version changes there would be an upgrade

**Comment by Perksey** [comment] 2023-05-01 03:46
Duplicate of #1199 

> Please don’t open issues asking when the next update is, please only open an issue if you have a genuine issue to report (like a bug or feature request). For everything else please use GitHub Discussions or Discord.

As for the experimental feed not targeting the next version, this has always been the case except for notable larger updates where we plan the release more carefully. The only valid versioning mechanism for the experimental feed is the build number, you should ignore the actual version number because we don't decide what vNext is until we're actually ready to release it.

**Closed by Perksey** 2023-05-01 03:46 UTC
