### ISSUE TITLE
imgui on android ERROR

### ISSUE THREAD

**Issue by LonerDo** [dotnet/Silk.NET#1166] opened 2022-12-09 06:14 UTC
use AndroidDemo and Silk.NET.OpenGLES.Extensions.ImGui

12-09 06:03:50.639 F/mono-rt ( 6047): [ERROR] FATAL UNHANDLED EXCEPTION: Silk.NET.SDL.SdlException: Couldn't find display mode match
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.SDL.Sdl.ThrowError()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.SDL.SdlContext.get_FramebufferSize()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.Sdl.SdlView.get_FramebufferSize()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.OpenGLES.Extensions.ImGui.ImGuiController.SetPerFrameImGuiData(Single deltaSeconds)
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.OpenGLES.Extensions.ImGui.ImGuiController.Update(Single deltaSeconds)
12-09 06:03:50.639 F/mono-rt ( 6047):    at AndroidDemo.MainActivity.OnRender(Double obj)
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.Internals.ViewImplementationBase.DoRender()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
12-09 06:03:50.639 F/mono-rt ( 6047):    at AndroidDemo.MainActivity.OnRun()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Run()
12-09 06:03:50.639 F/mono-rt ( 6047):    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Main()

**Comment by Perksey** [comment] 2023-01-10 16:33
Duplicate of #922

**Closed by Perksey** 2023-01-10 16:33 UTC
