### ISSUE TITLE
Desktop macOS binaries in the Silk.NET.MoltenVK.Native package

### ISSUE THREAD

**Issue by alexrp** [dotnet/Silk.NET#2012] opened 2024-04-05 19:16 UTC
As I mentioned in https://github.com/dotnet/Silk.NET/issues/2007#issuecomment-2038631442, this package doesn't currently have desktop macOS (`osx-arm64`, `osx-x64`) binaries. Unfortunately, I don't own a Mac myself, so I don't think there's much I can do here. So I'm logging this issue in the hope that someone who does might come across it and feel like contributing.

For this to be fully useful out of the box on Arm64, it would likely also require Silk.NET.Vulkan.Loader.Native to gain `osx-arm64` support - see #727.

**Comment by alexrp** [comment] 2024-04-05 23:43
@Perksey did this here: https://github.com/dotnet/Silk.NET/pull/1993/commits/7c6d2ebe9b1a42b3b3208bc11827d10e479b96f4

So this can be closed when that PR is merged.

**Comment by Perksey** [comment] 2024-04-06 00:06
Duplicate of #1660

**Closed by Perksey** 2024-04-06 00:06 UTC
Labels: enhancement
