### ISSUE TITLE
IKeyboard.IsKeyPressed(Key key) needs an scancode overload and to implement scancodes

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1235] opened 2023-01-17 11:52 UTC
# Summary of feature
Currently, you have to convert a scancode to the key in order to use this function. Scancodes are important when a specific key place becomes relevant instead of the actual character. Especially when it comes to international keyboards. German keyboards have y and z flipped which if you had something bound to y you'd have a misplaced keybind.

# Comments
Its super common for scancode support.

# Does this have a proposal?
No

**Comment by Perksey** [comment] 2023-01-17 12:44
Agree, I think this is one of the things that has been explicitly addressed in the 3.0 input proposal

**Comment by Beyley** [comment] 2023-01-17 20:40
> # Summary of feature
> 
> Currently, you have to convert a scancode to the key in order to use this function. Scancodes are important when a specific key place becomes relevant instead of the actual character. Especially when it comes to international keyboards. German keyboards have y and z flipped which if you had something bound to y you'd have a misplaced keybind.
> # Comments
> 
> Its super common for scancode support.
> # Does this have a proposal?
> 
> No

The behaviour of both input backends is to be keyboard-layout-agnostic (whether that be a good or a bad thing depends on the use-case), it should already be the case that the keys that are passed should be """scancodes""" as in they do not change position depending on the user's layout, if they do, then that's probably a bug and would be inconsistent with the intended behaviour of the key press and release events

**Comment by Perksey** [comment] 2023-01-21 17:46
@dotnet/silk-dotnet do we have any intention to address this in 2.X? This has already been addressed in 3.0.

**Comment by ThomasMiz** [comment] 2023-01-21 18:46
We could implement this like so:
- In the GLFW backend, we can easily use [glfwGetKeyScancode()](https://www.glfw.org/docs/latest/group__input.html#ga67ddd1b7dcbbaff03e4a76c0ea67103a)
- SDL will be more complicated as it has no such function. `SdlKeyboard.IsKeyPressed(Key key)` is implemented as a `List<Key> _keysDown`, with the list updated every time the keydown/keyup event occurs. We could do the same for scancodes, or maybe more appropiately turn this list into a list of scancodes and update the `SdlKeyboard` code like so:

```cs
public bool IsKeyPressed(Key key) => _keysDown.Contains(key);
public bool IsScancodePressed(int scancode) => _scancodesDown.Any(x => _keyMap.TryGetValue(x, out var skey) && key == skey);
```

**Comment by Perksey** [comment] 2023-01-21 19:00
Do we reckon anyone's going to implement that before 3.0 comes along though

**Comment by ThomasMiz** [comment] 2023-01-21 19:14
> Do we reckon anyone's going to implement that before 3.0 comes along though

I could give it a shot, seems like a very simple change. Are there any projects that use input and use `IsKeyPressed` to test this with? Mainly to make sure it's behavior doesn't change

**Comment by Perksey** [comment] 2023-01-21 19:21
I think there's an InputTest project in the lab

**Comment by ThomasMiz** [comment] 2023-01-21 19:33
There is, but it does not use `IsKeyPressed` lol

We can use some of the test projects from TrippyGL, the [SimpleShader3D](https://github.com/SilkCommunity/TrippyGL/tree/master/TrippyTests/SimpleShader3D) one uses `IsKeyPressed`

**Comment by Perksey** [comment] 2023-01-21 19:44
sounds good

**Comment by ThomasMiz** [comment] 2023-01-24 22:57
I've opened PR #1254 for this.

@Perksey @tilkinsc @Beyley Quick opinion question; which one do you prefer?
- Adding a fully separate function: `IKeyboard.IsScancodePressed(int scancode)`
- Or adding an overload: `IKeyboard.IsKeyPressed(int scancode)`

An argument for the latter might be that the `IKeyboard` key events report keys and scancodes together:
```cs
bool IsKeyPressed(Key key);
event Action<IKeyboard, Key, int>? KeyDown;
event Action<IKeyboard, Key, int>? KeyUp;
```

**Comment by tilkinsc** [comment] 2023-01-24 23:19
I prefer IsScancodePressed to not bring more meaning to Key as its truly a separate thing

**Comment by Beyley** [comment] 2023-01-25 00:23
> I've opened PR #1254 for this.
> 
> @Perksey @tilkinsc @Beyley Quick opinion question; which one do you prefer?
> - Adding a fully separate function: `IKeyboard.IsScancodePressed(int scancode)`
> - Or adding an overload: `IKeyboard.IsKeyPressed(int scancode)`
> 
> An argument for the latter might be that the `IKeyboard` key events report keys and scancodes together:
> ```cs
> bool IsKeyPressed(Key key);
> event Action<IKeyboard, Key, int>? KeyDown;
> event Action<IKeyboard, Key, int>? KeyUp;
> ```

i much prefer the separate function route, cleaner to understand

**Comment by Perksey** [comment] 2023-01-25 10:53
> IsScancodePressed 

Yes but you don't press a scancode, or at least I don't. I don't know what you have on your keyboard, but my keyboard has keys! I'm not even sure what a physical scancode would look like :P

**Comment by tilkinsc** [comment] 2023-01-26 20:43
![image](https://user-images.githubusercontent.com/7494772/214946205-8903d788-48e3-48bb-b8c1-7b58f911d59a.png)

Like this

**Comment by Perksey** [comment] 2023-01-27 10:40
That’s a funny looking keyboard you have there ;)

**Comment by tilkinsc** [comment] 2023-01-27 22:27
I mean surely you've seen dvorak and other keyboard layouts :)

**Comment by Beyley** [comment] 2023-03-13 09:46
#1254 has been merged

**Closed by Beyley** 2023-03-13 09:46 UTC
Labels: enhancement
