### ISSUE TITLE
Named issues about FormatB8G8R8A8Unorm

### ISSUE THREAD

**Issue by lindexi** [dotnet/Silk.NET#728] opened 2021-12-22 07:26 UTC
I think it should be `UNorm` not `Unorm`.

The `UNorm` means two words: unsigned-normalized.

**Comment by Perksey** [comment] 2021-12-22 07:45
Closing as “won’t fix” (and duplicate of #458 same underlying cause)

I agree, but
- these are generated bindings so we will have to special case these in the generator. Not a problem, but
- this would be a breaking change, which we are not prepared to do at this time.
- at least we’re consistently wrong throughout the library.

We will one day try and fix this as part of #458, but in the short/mid-term this will not be fixed.

**Closed by Perksey** 2021-12-22 07:45 UTC

**Comment by Perksey** [comment] 2021-12-22 07:46
#427 not #425 🙈

**Comment by lindexi** [comment] 2021-12-22 08:18
Thank you @Perksey
