### ISSUE TITLE
SDL2 Doesn't Respect WindowOptions.Position Member

### ISSUE THREAD

**Issue by tilkinsc** [dotnet/Silk.NET#1862] opened 2023-12-27 07:10 UTC
# Summary
It seems that SDL2 windows open at the same exact position every time. With the same exact code on GLFW I do not experience this issue.

# Steps to reproduce
- Platform: Windows
- Framework Version: .NET Core 8.0
- API: OpenGL (highest supported is 4.6)
```
<ItemGroup>
	<PackageReference Include="Silk.NET.Windowing" Version="2.20.0" />
	<PackageReference Include="Silk.NET.OpenGL" Version="2.20.0" />
	<PackageReference Include="Silk.NET.Input" Version="2.20.0" />
</ItemGroup>
```
```cs
public static void Main(string[] args)
{
	Window.PrioritizeSdl();
	
	WindowOptions options = WindowOptions.Default;
	options.Samples = config.Window.Samples;
	options.Size = new(800, 600);
	options.Position = new(1000, 400);
	options.Title = "Example";
	
	window = Window.Create(options);
	window.Load += OnLoad; // set up IInputContext, GL.GetApi(window)
	window.Render += OnRender; // glClear
	window.Update += OnUpdate; // empty
	window.Closing += OnClose; // key == Key.Escape window.Close()
	
	window.Run();
	window.Dispose();
}
```

**Comment by tilkinsc** [comment] 2023-12-27 07:39
I'm not sure but I think the Size and Position members are clashing. When I swap back and forth between Sdl and Glfw SDL will make the window GIANT sometimes exceeding the screen height. I recorded the width and height and window positions to analyze.

**Comment by Perksey** [comment] 2023-12-27 12:12
Is this an issue?

**Comment by Perksey** [comment] 2023-12-27 12:13
Ah sorry, misread the issue description, will look into this

**Comment by Perksey** [comment] 2024-03-20 20:05
I had a brief review of the code and I can't reproduce it. I've made some tweaks but don't think I've fixed anything. Nonetheless, the tweaked version will be in 2.21.

**Comment by tilkinsc** [comment] 2024-03-20 21:03
Windows 10 by the way. Surprised I neglected to say this.

**Comment by Perksey** [comment] 2024-03-20 21:07
I'll let you know when the tweaks are on the experimental feed to retest.

**Closed** 2024-03-21 18:32 UTC
Labels: bug
