### ISSUE TITLE
Webgpu dawn crash when calling AdapterGetLimits

### ISSUE THREAD

**Issue by EmilSV** [dotnet/Silk.NET#1601] opened 2023-08-04 17:41 UTC
# Summary
When your are using Dawn and calling AdapterGetLimits get an error and crash
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

# Steps to reproduce
- Platform: Windows
- API: WebGpu Dawn after commit https://dawn.googlesource.com/dawn/+/f3cac0d4538fe7c738cc4380f47f1cbc32c60324

# Comments
I did some investigating and found out that Dawn added a extra field to the WGPULimits sturct called maxBindGroupsPlusVertexBuffers  https://dawn.googlesource.com/dawn/+/f3cac0d4538fe7c738cc4380f47f1cbc32c60324 

and looks like Wgpu will add it in the future https://github.com/gfx-rs/wgpu/issues/2170 so at this moment they do not have the same size and because of that Dawn will write to protected memory.

**Comment by EmilSV** [comment] 2023-08-06 15:27
The problem is still on the newest version of silk.net as 
https://github.com/dotnet/Silk.NET/blob/main/src/WebGPU/Silk.NET.WebGPU/Structs/Limits.gen.cs
do have the property "MaxBindGroupsPlusVertexBuffers" which the newer version of Dawn uses.

And https://github.com/webgpu-native/webgpu-headers do yet have added "MaxBindGroupsPlusVertexBuffers" to the header file most likely because  Wgpu do not have it yet.

**Comment by Beyley** [comment] 2023-08-06 21:27
you should open an issue in the webgpu-headers repo about this, since we bind to the standardized headers, theres not much we can do about Dawn ignoring those and breaking ABI compat

**Comment by Perksey** [comment] 2023-08-21 21:52
Closing due to this being caused by a non-compliant driver.

**Closed by Perksey** 2023-08-21 21:52 UTC
Labels: bug, area-WebGPU
