### ISSUE TITLE
OpenAL Linux/Mac Library Files not being included on publish

### ISSUE THREAD

**Issue by Kuumba123** [dotnet/Silk.NET#1698] opened 2023-10-08 21:21 UTC
# Summary of feature
This is re-issue of issue that was immedilatly closed (https://github.com/dotnet/Silk.NET/issues/1697 and yes I already had everything setup in project/publish settings otherwise my program wouldn't have worked regardless if I was using Silk.NET) next time please dont just immediatly close issues , I wouldn't have opened either of these issues unless I know there was a problem. I guess Ill try to explain a bit more depth what the issue is. So normally when I want write a .NET 6 cross platform app I go to publish and then select the platform I want to publish for (mac , linux etc). Depending on witch platform I select the libraries (that generally get via nugget) I include in my C# project the libraries simply include different library files (dll,so files etc) based on the platform I am publishing for. However for some reason with Silk.NET (more specficly openAL) it doesnt include the propery library files if I publish for anything other than windows so if I try to run the program Ill get an error as soon as it tries to run any code that uses Silk.NET. Now I could just go in the source code and grab the correct library files (libopenal.so and libopenal.dylib in my case) and just copy them to the same directory as the Linux and Mac EXE witch fixes the problems. I could also just force users to just install openAL but I dont like doing that (especally for linux cause of all the distros). But preferable this should all be taken care of by the libraries and not by me copying library files and messing with my the files included in my project. Anyways hopefully you folks understand what Im talking about.

# Does this have a proposal?
just have the library files be include on linux/mac publish by default just like it is for Windows publish.

**Comment by Perksey** [comment] 2023-10-08 21:25
Closing as duplicate of #1697

**Closed by Perksey** 2023-10-08 21:25 UTC
Labels: enhancement
