### ISSUE TITLE
Validation layers not found vulkan

### ISSUE THREAD

**Issue by ThisIsHimaksh** [dotnet/Silk.NET#1274] opened 2023-02-07 13:08 UTC
# Summary
Validation layers are always not found no matter what.

# Steps to reproduce
- Platform: MacOS
- Framework Version: .NET Core 7
- API: Vulkan 
- API Version: Vulkan 1.2
1. First I used <a href="https://github.com/dfkeenan/SilkVulkanTutorial"> these samples </a>
2. Then on running the validation layers sample it return the Exception: validation layers requested, but not available! 

# Comments
On using the lwjgl vulkan bindings I found out that lwjgl actually bypasses the vulkan loader which does know how to find validation layers. So is there anyway to make Silk.NET load the vulkan-loader.

**Comment by ohtrobinson** [comment] 2023-02-07 13:12
This sounds like it is more of an issue with MoltenVK rather than Silk. Silk just provides raw bindings to the APIs, and won't have anything to do with the validation layers.

I can see an open issue on the samples you linked about adding M1 support, which may or may not be the cause of the issue, but it is up to the maintainer of the samples to add support for this.

**Comment by Perksey** [comment] 2023-02-07 13:29
This will be fixed in 2.17 where we always load the Vulkan loader on macOS and is already in main.

**Closed by Perksey** 2023-02-07 13:29 UTC
Labels: bug
