### ISSUE TITLE
Enable Trimming

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#541] opened 2021-07-05 20:16 UTC
See [the docs](https://docs.microsoft.com/en-us/dotnet/core/deploying/prepare-libraries-for-trimming) for trimming. Doing so is breaking and we therefore need to do it until 3.0 - and probably throughout the 3.0 development cycle.

**Comment by Perksey** [comment] 2021-07-05 20:47
Duplicate of #305

**Closed by Perksey** 2021-07-05 20:47 UTC
