### ISSUE TITLE
DirectWrite and WIC

### ISSUE THREAD

**Issue by RoccoZero** [dotnet/Silk.NET#1263] opened 2023-01-31 15:11 UTC
please add DirectWrite and WIC
my project uses ID2D1RenderTarget so also need IDWriteFactory and IWICImagingFactory
now temporarily using some api from [Vortice](https://github.com/amerkoleci/Vortice.Windows) but I don't like this approach

**Comment by Perksey** [comment] 2023-02-01 12:51
Duplicate of #813

**Closed by Perksey** 2023-02-01 12:51 UTC
Labels: enhancement
