### ISSUE TITLE
Doesn't work on NixOS

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/Silk.NET#1491] opened 2023-06-07 19:56 UTC
# Summary
A summary of the issue you're experiencing.
I am getting this when running silk.net on nixos

```
Exception has occurred: CLR/System.PlatformNotSupportedException
An unhandled exception of type 'System.PlatformNotSupportedException' occurred in Silk.NET.Windowing.Common.dll: 'Couldn't find a suitable window platform. (GlfwPlatform - not applicable, SdlPlatform - not applicable) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html'
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at Window..ctor() in /home/shadowblitz16/Documents/source/C#/GameSharp/Engine/Scene/Node/Window.cs:line 29
   at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/C#/GameSharp/Editor/Program.cs:line 4
```

# Steps to reproduce
- Platform: Mobile/Desktop
- Framework Version: .NET 7
- API Just GLFW right now

# Code
```cs
    public Window()
    {
        ////////////////////////////////////////////////////
        // CRASH HERE
        ////////////////////////////////////////////////////
        _window = Silk.NET.Windowing.Window.Create(new WindowOptions()
        {
            Size  = new Vector2D<int>(720, 480),
            Title = "Window",
            VSync = true
        });
        _window.Load    += ( ) =>
        {
            OnReady();  
        };
        _window.Update  += (e) =>
        {
            OnUpdate((float)e);  
        };
        _window.Render  += (e) =>
        {
            OnRender((float)e);  
        };
        _window.Closing += ( ) =>
        {
            Dispose();
        };
        
        _window.Move    += (e) =>
        {
            OnMove(e);
        };
        _window.Resize  += (e) =>
        {
            OnResize(e);
        };
    }
```

**Comment by Beyley** [comment] 2023-06-07 20:25
> # Summary
> 
> A summary of the issue you're experiencing. I am getting this when running silk.net on nixos
> 
> ```
> Exception has occurred: CLR/System.PlatformNotSupportedException
> An unhandled exception of type 'System.PlatformNotSupportedException' occurred in Silk.NET.Windowing.Common.dll: 'Couldn't find a suitable window platform. (GlfwPlatform - not applicable, SdlPlatform - not applicable) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html'
>    at Silk.NET.Windowing.Window.Create(WindowOptions options)
>    at Window..ctor() in /home/shadowblitz16/Documents/source/C#/GameSharp/Engine/Scene/Node/Window.cs:line 29
>    at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/C#/GameSharp/Editor/Program.cs:line 4
> ```
> 
> # Steps to reproduce
> 
>     * Platform: Mobile/Desktop
> 
>     * Framework Version: .NET 7
> 
>     * API Just GLFW right now
> 
> 
> # Code
> 
> ```cs
>     public Window()
>     {
>         ////////////////////////////////////////////////////
>         // CRASH HERE
>         ////////////////////////////////////////////////////
>         _window = Silk.NET.Windowing.Window.Create(new WindowOptions()
>         {
>             Size  = new Vector2D<int>(720, 480),
>             Title = "Window",
>             VSync = true
>         });
>         _window.Load    += ( ) =>
>         {
>             OnReady();  
>         };
>         _window.Update  += (e) =>
>         {
>             OnUpdate((float)e);  
>         };
>         _window.Render  += (e) =>
>         {
>             OnRender((float)e);  
>         };
>         _window.Closing += ( ) =>
>         {
>             Dispose();
>         };
>         
>         _window.Move    += (e) =>
>         {
>             OnMove(e);
>         };
>         _window.Resize  += (e) =>
>         {
>             OnResize(e);
>         };
>     }
> ```

I'll likely not get to debugging this myself for awhile, what is the output of the app when `LD_DEBUG=libs`? its likely just a missing dependency, glance through there and do some greps through it, and it should be obvious what the problem is

**Comment by Shadowblitz16** [comment] 2023-06-08 00:43
> > # Summary
> > A summary of the issue you're experiencing. I am getting this when running silk.net on nixos
> > ```
> > Exception has occurred: CLR/System.PlatformNotSupportedException
> > An unhandled exception of type 'System.PlatformNotSupportedException' occurred in Silk.NET.Windowing.Common.dll: 'Couldn't find a suitable window platform. (GlfwPlatform - not applicable, SdlPlatform - not applicable) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html'
> >    at Silk.NET.Windowing.Window.Create(WindowOptions options)
> >    at Window..ctor() in /home/shadowblitz16/Documents/source/C#/GameSharp/Engine/Scene/Node/Window.cs:line 29
> >    at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/C#/GameSharp/Editor/Program.cs:line 4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Steps to reproduce
> > ```
> > * Platform: Mobile/Desktop
> > 
> > * Framework Version: .NET 7
> > 
> > * API Just GLFW right now
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # Code
> > ```cs
> >     public Window()
> >     {
> >         ////////////////////////////////////////////////////
> >         // CRASH HERE
> >         ////////////////////////////////////////////////////
> >         _window = Silk.NET.Windowing.Window.Create(new WindowOptions()
> >         {
> >             Size  = new Vector2D<int>(720, 480),
> >             Title = "Window",
> >             VSync = true
> >         });
> >         _window.Load    += ( ) =>
> >         {
> >             OnReady();  
> >         };
> >         _window.Update  += (e) =>
> >         {
> >             OnUpdate((float)e);  
> >         };
> >         _window.Render  += (e) =>
> >         {
> >             OnRender((float)e);  
> >         };
> >         _window.Closing += ( ) =>
> >         {
> >             Dispose();
> >         };
> >         
> >         _window.Move    += (e) =>
> >         {
> >             OnMove(e);
> >         };
> >         _window.Resize  += (e) =>
> >         {
> >             OnResize(e);
> >         };
> >     }
> > ```
> 
> I'll likely not get to debugging this myself for awhile, what is the output of the app when `LD_DEBUG=libs`? its likely just a missing dependency, glance through there and do some greps through it, and it should be obvious what the problem is

I still don't know what you mean by `LD_DEBUG=libs` I am not a advanced terminal user
However I think this is a bigger issue. I just tried raylib-cs and it doesn't work either I think it has to do with nuget not working correctly on nixos.

I am considering moving back to kubuntu so feel free to close this. 
I think in order to fix it, something has to be done on the nix os side.

**Comment by Beyley** [comment] 2023-06-08 00:45
You need to set the environment variable named `LD_DEBUG` to `libs`, as i stated in discord

**Comment by Shadowblitz16** [comment] 2023-06-08 00:50
> You need to set the environment variable named `LD_DEBUG` to `libs`, as i stated in discord

how do I do that?

**Comment by Perksey** [comment] 2023-06-13 12:12
Closing as resolved

**Closed by Perksey** 2023-06-13 12:12 UTC
Labels: bug

**Comment by Jemy191** [comment] 2025-07-23 03:13
I'm posting this comment so other that encounter this problem can have more info :)

There is two way to fix the lib not found issue.

#### First with nix-ld:

Add this to your nix config:
```nix
programs = {
  nix-ld.enable = true;
  nix-ld.libraries = with pkgs; [
    glfw
    assimp # If you use it
  ];
};
```

And add this to launchSettings.json... You can also override the global `LD_LIBRARY_PATH` but that not recommended.
```json
"environmentVariables": {
  "LD_LIBRARY_PATH": "%LD_LIBRARY_PATH%;%NIX_LD_LIBRARY_PATH%"
}
```

#### Second, with a nix-shell that use buildFHSEnv:

in your user or system package, add:
```nix
packages = with pkgs; [
  (pkgs.buildFHSEnv {
    name = "silk-fhs";
    runScript = "bash"; # this could also be your ide or that app
    targetPkgs = pkgs: with pkgs; [ glfw assimp ];
  })
];
```
Just start the shell with the `silk-fhs` command and run the app from that shell.
